# Generated by Django 5.0.6 on 2024-06-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('GR', 'Groceries'), ('SN', 'Snacks'), ('HO', 'Home'), ('UT', 'Utilities'), ('RE', 'Rent'), ('CH', 'Child'), ('PE', 'Pets'), ('CL', 'Clothes'), ('SU', 'Subscriptions'), ('PH', 'Phone'), ('CA', 'Car'), ('GA', 'Gas'), ('TP', 'Transportation'), ('TR', 'Travel'), ('HE', 'Health'), ('SC', 'Selfcare'), ('EN', 'Entertainment'), ('WK', 'Work'), ('IN', 'Insurance'), ('SA', 'Savings'), ('IV', 'Investments'), ('LO', 'Loans'), ('RT', 'Retirement'), ('ED', 'Education'), ('MI', 'Misc'), ('OT', 'Other')], default='MI', max_length=2),
        ),
    ]
