# Generated by Django 5.0.6 on 2024-07-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_alter_transaction_transaction_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
